Render generated jsx/html via iframe with (zoom in and out)
Corei13/reframe pull request #22
Opened 2022-03-14 16:11 UTC by ranit43

New: https://www.loom.com/share/a65cc87e792f47c4bf1e36be69b80ee8
Old: https://www.loom.com/share/dd05f52ad3a849eabe1089c62dcdb062

2022-03-14 16:33 UTC, ovis96 commented on lib/editor/index.tsx
> +    "-moz-transform": `scale(${zoomValue})`,
zoomValue is a state we should not use here, b/c if zoomValue changes it'll not do anything here. so better we have a initialZoomValue = 0.75 and use it wherever we need 0.75

2022-03-14 16:34 UTC, ovis96 commented on lib/editor/index.tsx
> +  const [zoomValue, setZoomValue] = React.useState(0.75);
same here use create a const initialZoomValue = 0.75 and use it here, b/c we might need to change it in the future

2022-03-14 16:36 UTC, ovis96 commented on lib/editor/index.tsx
> +                  setZoomValue(zoomValue + 0.25);
can we just calculate this incremented zoomValue and use it everywhere else? b/c same repeated calculations are below

2022-03-14 16:39 UTC, ovis96 commented on lib/editor/index.tsx
> +                    "-webkit-transform-origin": " 0 0",
nits: these origin values did not change at all, we can do like setIframeStyle({ ...iframeStyle, "-ms-zoom": incrementedZoomValue}) what do you think?

2022-03-14 16:39 UTC, ovis96 commented on styles/globals.css
> +  width: 800px;
shouldn't it be 100% or something? why it is hardcoded?

2022-03-14 16:40 UTC, ovis96 commented on styles/globals.css
> +  width: 800px;
i guess that's why we are getting a horizontal scrollbar that we might not want?

2022-03-14 16:58 UTC, ovis96 commented on lib/editor/index.tsx
> +  const [iframeStyle, setIframeStyle] = React.useState({
I think we don't need this iframeStyle in a state, we can always create this from zoomValue right? what do ya think?

2022-03-14 16:59 UTC, ovis96 commented on lib/editor/index.tsx
> +    "-moz-transform": `scale(${zoomValue})`,
if we revert making iframStyle a state we can ignore ^^ comment

2022-03-14 18:47 UTC, Corei13 requested changes
looks great! this seems to correctly encapsulate styles inside iframe so that parent styles are not leaking inside.

2022-03-14 18:47 UTC, Corei13 commented on styles/globals.css
> +  width: 800px;
@ranit43 let's avoid global styles

2022-03-14 18:47 UTC, Corei13 commented on lib/editor/index.tsx
> +  const [iframeStyle, setIframeStyle] = React.useState({
@ranit43 this is not necessary since iframeStyle can be derived from zoomValue.

In general, if you find yourself updating two states at once all the time, this is a signal that there might be only one true state and another one is simply derived value.

2022-03-14 18:47 UTC, Corei13 commented on lib/editor/index.tsx
> +            <iframe id="frame" src={generatedPreviewLink} style={iframeStyle}>
Let's use @base/Iframe instead

2022-03-15 08:43 UTC, ranit43 commented on lib/editor/index.tsx
> +            <iframe id="frame" src={generatedPreviewLink} style={iframeStyle}>
okay.

2022-03-15 10:57 UTC, ranit43 commented on lib/editor/index.tsx
> +    "-moz-transform": `scale(${zoomValue})`,
avoided creating `initialZoomValue` as we are not using it anymore without the initialization part.

2022-03-15 10:58 UTC, ranit43 commented on lib/editor/index.tsx
> +  const [zoomValue, setZoomValue] = React.useState(0.75);
avoided creating `initialZoomValue` as we are not using it anymore without the initialization part.

2022-03-15 10:59 UTC, ranit43 commented on lib/editor/index.tsx
> +                  setZoomValue(zoomValue + 0.25);
yes added function `getIframeStyle` for generating the iframe styles.

2022-03-15 10:59 UTC, ranit43 commented on lib/editor/index.tsx
> +                    "-webkit-transform-origin": " 0 0",
moved it to the base-iframe style.

2022-03-15 11:07 UTC, ranit43 commented on lib/editor/index.tsx
> +  const [iframeStyle, setIframeStyle] = React.useState({
yes, removed it. Thanks for pointing out the pattern.

>  if you find yourself updating two states at once all the time, this is a signal that there might be only one true state and another one is simply derived value.

2022-03-15 11:09 UTC, ranit43 commented on styles/globals.css
> +  width: 800px;
> shouldn't it be 100% or something? why it is hardcoded?
@ovis96  It was hardcoded for showing it is smaller than the actual and how the scaling takes effect. But yes, it should not be hardcoded. BTW, `100%` didn't fix the horizontal scrollbar. I think it's coming from one of the main rendering components.  Gotta check more. Maybe we should create a ticket if it's not a direct fix.

2022-03-15 12:08 UTC, Corei13 approved these changes
looks good, lets merge this in

2022-03-15 12:08 UTC, Corei13 commented on lib/editor/index.tsx
> +  const getIframeStyle = useCallback(
I think a memo makes more sense than callback here

2022-03-15 12:25 UTC, ranit43 commented on styles/globals.css
> +  width: 800px;
Avoided global style.

2022-03-15 12:26 UTC, ranit43 commented on lib/editor/index.tsx
> +                  setZoomValue(zoomValue - 0.25);
updated it.

2022-03-15 12:29 UTC, ranit43 commented on lib/editor/index.tsx
> +  const getIframeStyle = useCallback(
updated it to a memo.

2022-03-15 12:32 UTC, merged